import type { ResearchRun } from "./researchTypes";

export const demoResearchRun: ResearchRun = {
  run_id: "run_socal_coating_demo",
  status: "done",
  project_facts: {
    facility: "Los Angeles County manufacturing facility",
    naics: "332813",
    sic: "3471",
    equipment: "new coating booth",
    chemical: "60 gallons flammable solvent",
    waste_stream: "spent solvent, monthly quantity missing",
    disturbance_acres: 0,
  },
  jurisdiction_stack: ["SCAQMD", "California Water Boards", "Local CUPA"],
  coverage_family_statuses: [
    {
      id: "CF-AIR",
      family: "air",
      status: "active",
      reason: "The project adds a coating booth that may be new emitting equipment.",
      project_facts_considered: ["new coating booth", "SCAQMD jurisdiction"],
      missing_facts: [],
    },
    {
      id: "CF-STORM",
      family: "stormwater",
      status: "active",
      reason: "The facility has SIC/NAICS facts that may map to industrial stormwater coverage.",
      project_facts_considered: ["SIC 3471", "NAICS 332813", "0 acres disturbed"],
      missing_facts: [],
    },
    {
      id: "CF-HAZMAT",
      family: "hazmat",
      status: "active",
      reason: "The project stores 60 gallons of hazardous liquid.",
      project_facts_considered: ["60 gallons flammable solvent"],
      missing_facts: [],
    },
    {
      id: "CF-WASTE",
      family: "waste",
      status: "blocked_missing_fact",
      reason: "Spent solvent is present, but monthly generation quantity is missing.",
      project_facts_considered: ["spent solvent"],
      missing_facts: ["kg_per_month"],
    },
    {
      id: "CF-WASTEWATER",
      family: "wastewater",
      status: "out_of_scope",
      reason: "No process wastewater discharge fact was provided in the seeded scenario.",
      project_facts_considered: ["no discharge described"],
      missing_facts: [],
    },
  ],
  regulatory_angles: [
    {
      id: "A-AIR-EMITTING-EQUIPMENT",
      family: "air",
      label: "New or modified emitting equipment",
      reason: "A coating booth may emit regulated pollutants and require authorization.",
      triggering_facts: ["coating booth", "SCAQMD jurisdiction"],
      status: "active",
    },
    {
      id: "A-HAZMAT-HMBP",
      family: "hazmat",
      label: "Hazardous material business plan threshold",
      reason: "The stored liquid quantity is near a known gallon threshold.",
      triggering_facts: ["60 gallons flammable solvent"],
      status: "active",
    },
    {
      id: "A-WASTE-GENERATOR",
      family: "waste",
      label: "Hazardous waste generator status",
      reason: "Spent solvent exists, but monthly generation quantity is missing.",
      triggering_facts: ["spent solvent"],
      status: "blocked_missing_fact",
    },
  ],
  research_graph: [
    {
      id: "H-AIR-001",
      angle_id: "A-AIR-EMITTING-EQUIPMENT",
      question: "Does the new coating booth require an SCAQMD Permit to Construct?",
      claim_to_test: "The coating booth may require SCAQMD authorization before installation.",
      required_facts: ["equipment type", "jurisdiction", "emissions or exemption facts"],
      expected_source_type: "regulation",
      success_criteria: ["official source", "trigger quote", "human-review fallback"],
      dependencies: [],
    },
    {
      id: "H-HAZMAT-001",
      angle_id: "A-HAZMAT-HMBP",
      question: "Does 60 gallons of hazardous liquid trigger HMBP/CERS obligations?",
      claim_to_test: "HMBP applies because 60 gallons is above the 55 gallon threshold.",
      required_facts: ["chemical quantity", "unit", "hazard class"],
      expected_source_type: "agency_guidance",
      success_criteria: ["official source", "threshold quote", "math check"],
      dependencies: [],
    },
    {
      id: "H-WASTE-001",
      angle_id: "A-WASTE-GENERATOR",
      question: "Can generator status be determined without monthly spent solvent quantity?",
      required_facts: ["kg_per_month"],
      expected_source_type: "regulation",
      success_criteria: ["missing-fact blocker remains visible"],
      dependencies: [],
    },
  ],
  research_tasks: [
    {
      task_id: "T-AIR-001",
      hypothesis_id: "H-AIR-001",
      assigned_agent: "air_researcher",
      allowed_tools: ["official_web_fetch", "pdf_extract", "citation_extractor"],
      blocked_tools: ["memory_write", "final_report_write"],
      budget: { max_sources: 5, max_runtime_seconds: 90, max_model_calls: 6 },
    },
    {
      task_id: "T-HAZMAT-001",
      hypothesis_id: "H-HAZMAT-001",
      assigned_agent: "hazmat_researcher",
      allowed_tools: ["official_web_fetch", "citation_extractor", "predicate_math"],
      blocked_tools: ["memory_write", "final_report_write"],
      budget: { max_sources: 4, max_runtime_seconds: 90, max_model_calls: 6 },
    },
    {
      task_id: "T-WASTE-001",
      hypothesis_id: "H-WASTE-001",
      assigned_agent: "waste_researcher",
      allowed_tools: ["missing_fact_detector"],
      blocked_tools: ["memory_write", "final_report_write"],
      budget: { max_sources: 2, max_runtime_seconds: 45, max_model_calls: 3 },
    },
  ],
  evidence_bundles: [
    {
      hypothesis_id: "H-HAZMAT-001",
      sources: [
        {
          url: "https://cers.calepa.ca.gov/",
          source_name: "California CERS hazardous materials guidance",
          authority_rank: 1,
          fetched_at: "2026-05-30T10:00:00Z",
          content_hash: "sha256:demo-hmbp-threshold",
          effective_date: null,
          quote: "Businesses must submit information for hazardous materials at or above threshold quantities.",
        },
      ],
      extracted_claims: [
        {
          field: "initial_claim",
          value: "HMBP applies to all hazardous material storage.",
          source_url: "https://cers.calepa.ca.gov/",
          quote: "Businesses must submit information for hazardous materials at or above threshold quantities.",
          confidence: 0.62,
        },
        {
          field: "repaired_threshold",
          value: "60 gallons is above the 55 gallon hazardous liquid threshold.",
          source_url: "https://cers.calepa.ca.gov/",
          quote: "Businesses must submit information for hazardous materials at or above threshold quantities.",
          confidence: 0.88,
        },
      ],
      researcher_conclusion: "applies",
      uncertainties: [],
    },
  ],
  verification_verdicts: [
    {
      hypothesis_id: "H-HAZMAT-001",
      verdict: "pass",
      checks: {
        authority: { pass: true, reason: "Official California reporting system source." },
        grounding_initial: { pass: false, reason: "The quote mentions thresholds, not all storage." },
        grounding_repaired: { pass: true, reason: "The repaired claim compares customer quantity to threshold." },
        predicate_math: { pass: true, reason: "60 gallons is greater than 55 gallons." },
      },
      confidence: 0.88,
      repair_tickets: [],
    },
    {
      hypothesis_id: "H-WASTE-001",
      verdict: "needs_review",
      checks: {
        missing_facts: { pass: false, reason: "Monthly spent solvent quantity is missing." },
      },
      confidence: 0.41,
      repair_tickets: [],
    },
  ],
  repair_tickets: [
    {
      ticket_id: "R-HAZMAT-001",
      hypothesis_id: "H-HAZMAT-001",
      failure_type: "grounding_failed",
      failed_check: "grounding_initial",
      observed_problem: "The extracted claim said all storage, but the quote only supports threshold-based reporting.",
      repair_action: "Rerun extraction with quote-constrained threshold comparison.",
      max_attempts_remaining: 1,
    },
  ],
  determinations: [
    {
      requirement: "HMBP/CERS hazardous materials reporting",
      applies: "yes",
      trigger: "Hazardous liquid quantity exceeds threshold",
      project_fact: "60 gallons flammable solvent",
      citation: "California CERS threshold guidance",
      quote: "Businesses must submit information for hazardous materials at or above threshold quantities.",
      source_url: "https://cers.calepa.ca.gov/",
      confidence: 0.88,
      verified: true,
      review_flag: false,
      hypothesis_id: "H-HAZMAT-001",
    },
    {
      requirement: "Hazardous waste generator status",
      applies: "needs_review",
      trigger: "Spent solvent waste stream",
      project_fact: "Monthly quantity missing",
      citation: "Missing fact",
      quote: "Monthly spent solvent generation quantity is required before status can be determined.",
      source_url: "",
      confidence: 0.41,
      verified: false,
      review_flag: true,
      hypothesis_id: "H-WASTE-001",
    },
  ],
  trace_events: [
    {
      id: "EVT-001",
      run_id: "run_socal_coating_demo",
      ts: "2026-05-30T10:00:00Z",
      actor: "Scope Agent",
      phase: "scope",
      status: "done",
      message: "ScopePack created for Los Angeles County manufacturing facility.",
    },
    {
      id: "EVT-002",
      run_id: "run_socal_coating_demo",
      ts: "2026-05-30T10:00:02Z",
      actor: "Orchestrator",
      phase: "planning",
      status: "done",
      message: "Coverage floor inspected air, stormwater, hazmat, waste, and wastewater.",
    },
    {
      id: "EVT-003",
      run_id: "run_socal_coating_demo",
      ts: "2026-05-30T10:00:04Z",
      actor: "Worker Pool",
      phase: "research",
      status: "running",
      message: "3 demo research workers spawned from scoped task graph.",
    },
    {
      id: "EVT-004",
      run_id: "run_socal_coating_demo",
      ts: "2026-05-30T10:00:12Z",
      actor: "Verifier",
      phase: "verification",
      status: "failed",
      message: "HMBP grounding failed: quote did not support all-storage claim.",
      artifact_id: "R-HAZMAT-001",
    },
    {
      id: "EVT-005",
      run_id: "run_socal_coating_demo",
      ts: "2026-05-30T10:00:16Z",
      actor: "Orchestrator",
      phase: "repair",
      status: "done",
      message: "RepairTicket created and scoped threshold extraction rerun.",
      artifact_id: "R-HAZMAT-001",
    },
    {
      id: "EVT-006",
      run_id: "run_socal_coating_demo",
      ts: "2026-05-30T10:00:24Z",
      actor: "Synthesis Agent",
      phase: "matrix",
      status: "done",
      message: "Final matrix created with verified HMBP row and waste needs-review row.",
    },
  ],
  report_markdown:
    "The seeded facility change triggered a dynamic research graph across air, stormwater, hazmat, waste, and wastewater. The HMBP row was repaired after the verifier rejected an overbroad claim. Hazardous waste generator status remains needs-review because monthly waste quantity is missing.",
};
